"""Add SubcatAnalysis table

Revision ID: 7b2978783b04
Revises: e51efc2cc9a8
Create Date: 2026-02-17 15:34:53.652410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2978783b04'
down_revision: Union[str, None] = 'e51efc2cc9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcat_analysis',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('model_group', sa.String(length=150), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('subcategory_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_comments', sa.String(length=500), nullable=True),
    sa.Column('proposal_version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcat_analysis')
    # ### end Alembic commands ###
