"""Refine schema with analytics fields

Revision ID: 89c477daf92e
Revises: 7b2978783b04
Create Date: 2026-02-17 15:45:05.678531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c477daf92e'
down_revision: Union[str, None] = '7b2978783b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_files', sa.Column('file_metadata', sa.JSON(), nullable=True))
    op.add_column('model_groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('subcat_analysis', sa.Column('estimated_impact', sa.JSON(), nullable=True))
    op.add_column('subcat_analysis', sa.Column('configuration', sa.JSON(), nullable=True))
    op.add_column('subcat_analysis', sa.Column('linked_artifacts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcat_analysis', 'linked_artifacts')
    op.drop_column('subcat_analysis', 'configuration')
    op.drop_column('subcat_analysis', 'estimated_impact')
    op.drop_column('model_groups', 'is_active')
    op.drop_column('model_files', 'file_metadata')
    # ### end Alembic commands ###
