"""Add ModelGroup and file_guid

Revision ID: e51efc2cc9a8
Revises: 
Create Date: 2026-02-17 15:21:10.476029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51efc2cc9a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=150), nullable=False),
    sa.Column('l2_values', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.add_column('model_files', sa.Column('file_guid', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_model_files_file_guid'), 'model_files', ['file_guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_files_file_guid'), table_name='model_files')
    op.drop_column('model_files', 'file_guid')
    op.drop_table('model_groups')
    # ### end Alembic commands ###
